### ISSUE TITLE
A way to tracking errors 

### ISSUE THREAD

**Issue by alihassan161820** [directus/directus#11474]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I tried to integrate with sentry in init hooks to track 500 errors that printed in console but it didn't catch any error so i there any hook to catch threw  errors in it ?

### To Reproduce

module.exports = function ({init}, {services, env, database}) {
    init('routes.before', async (app) => {
        Sentry.init({ dsn: "https://------------------------------------------@o1037532.ingest.sentry.io/6005525" });
        app.use(Sentry.Handlers.requestHandler());
        app.use(Sentry.Handlers.errorHandler());
    });
};

### What version of Directus are you using?

9.3.1

### What version of Node.js are you using?

16

### What database are you using?

mysql

### What browser are you using?

chrome

### What operating system are you using?

ubuntu

### How are you deploying Directus?

docker
