### ISSUE TITLE
Apply schema fails when using meta.options.filter (and sometimes meta.options.languageField)

### ISSUE THREAD

**Issue by smonn** [directus/directus#11943]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When one or more fields contain the filter option, the `directus schema apply` command fails.

Edit: this might be similar to #10518 but in my case the reason appear to be different. Unsure if it's related.

### To Reproduce

[Check this gist for snapshot files](https://gist.github.com/smonn/6a223809c51bda7e4622aebf200ab137)

The steps go something like this:

1. Setup a new Directus instance
2. Create Article and Category collections
3. Setup translations for each
4. Setup a one-to-many relations from Article to Category
5. Generate a schema snapshot (simulating sharing schema with other devs)
6. Add field `hidden` on Category and add filter on the `article.category` field using the new field
7. Generate a new schema snapshot in a new file
8. Simulate another dev, recreate the DB using the initial snapshot
9. Apply the second snapshot and see error

I wasn't always able to reproduce the steps above, but the snapshot files in the Gist _should_ trigger the error. But let me know if they don't and I'll try again.

### Errors Shown

```
21:30:52 🚨 Failed to create field "article.category"
21:30:52 🚨 Undefined binding(s) detected when compiling FIRST. Undefined column(s): [field] query: select "id" from "directus_fields" where "collection" = ? and "field" = ? limit ?
Error: Undefined binding(s) detected when compiling FIRST. Undefined column(s): [field] query: select "id" from "directus_fields" where "collection" = ? and "field" = ? limit ?
    at QueryCompiler_PG.toSQL (/Users/simon/projects/algorand/algomart/node_modules/directus/node_modules/knex/lib/query/querycompiler.js:110:13)
    at Builder.toSQL (/Users/simon/projects/algorand/algomart/node_modules/directus/node_modules/knex/lib/query/querybuilder.js:83:44)
    at ensureConnectionCallback (/Users/simon/projects/algorand/algomart/node_modules/directus/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:4:30)
    at Runner.ensureConnection (/Users/simon/projects/algorand/algomart/node_modules/directus/node_modules/knex/lib/execution/runner.js:272:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Runner.run (/Users/simon/projects/algorand/algomart/node_modules/directus/node_modules/knex/lib/execution/runner.js:30:19)
    at async FieldsService.createField (/Users/simon/projects/algorand/algomart/node_modules/directus/dist/services/fields.js:203:33)
    at async /Users/simon/projects/algorand/algomart/node_modules/directus/dist/utils/apply-snapshot.js:71:21
```

### What version of Directus are you using?

9.5.2

### What version of Node.js are you using?

16.14.0

### What database are you using?

Postgres 14

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment]
As this issue correctly pointed out it happening when there are changes to `meta.options`, it is indeed a duplicate of #10518. You may refer to #12712 for more info or the reasoning behind it.
