### ISSUE TITLE
File meta aren't updated on file update

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#12049]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

If you update a fiele (e.g crop) the file size changes. The file-meta aren't updated and stay the same.

### To Reproduce

* Upload a file
* Check file size in directus and on system
* Edit the file in directus (e.g crop drastically)
* View file size on system and in directus
* --> The file is way smaller now, but directus doesn't updates the file

### What version of Directus are you using?

9.0.6

### What version of Node.js are you using?

16.14

### What database are you using?

MySql 8

### What browser are you using?

Chrome

### What operating system are you using?

macOs

### How are you deploying Directus?

locally

**Comment by benhaynes** [comment]
Good catch! I wonder if the same things happens when you _replace_ a file asset?

**Comment by rijkvanzanten** [comment]
> Good catch! I wonder if the same things happens when you _replace_ a file asset?

The app editing experience uses the file replace under the hood, so yes

**Comment by rijkvanzanten** [comment]
I believe this was since fixed. I'm no longer able to reproduce this on v9.8.0
