### ISSUE TITLE
App Onboarding

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#19797]
When new admin users login to Directus for the first time, it's a fully blank canvas. It's oftentimes a little overwhelming to know where to start. To improve on this, we want to add an onboarding flow for new projects/users to help admin users configure their project.

Final RFC coming soon!
```[tasklist]
### Tasks
- [x] https://github.com/directus/directus/issues/19935
- [x] https://github.com/directus/directus/issues/19936
- [x] https://github.com/directus/directus/issues/19937
- [x] https://github.com/directus/directus/issues/19938
- [x] https://github.com/directus/directus/issues/19982
- [ ] https://github.com/directus/directus/issues/19987
- [ ] https://github.com/directus/directus/issues/19983
- [ ] https://github.com/directus/directus/issues/19985
- [ ] https://github.com/directus/directus/issues/19986
- [ ] https://github.com/directus/directus/issues/20027
- [ ] https://github.com/directus/directus/issues/20028
- [ ] https://github.com/directus/directus/issues/20050
- [ ] https://github.com/directus/directus/issues/20046
- [ ] https://github.com/directus/directus/issues/19984
- [ ] https://github.com/directus/directus/issues/21133
```

**Comment by kinged007** [comment]
It would be nice if we could also create an onboarding process for new users that join the instance - eg. a customer or client (end user). For the moment I am doing this using a simple Singleton page with only read permissions, with a bunch of Notices to explain things and Buttons to go to the relevant collection. Once onboarding is complete, the Singleton is still visible in the menu unfortunately.

**Comment by DanielBiegler** [comment]
Yeah, that idea has been thrown around internally too and I'd love to make this happen but there's a huge list of unknowns for the actual detailed design and implementation. I'd welcome anyone making a thorough Feature Request for this.

That being said, Directus is super duper flexible so _technically_ speaking, as of right now, you _could_ make an extension with hooks/modules/redirects/migrations that implements an onboarding experience for your users. It's just a matter of effort. :smile:
