### ISSUE TITLE
Content Versioning

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#19796]
Overarching issue for individual tasks left todo to complete the content versioning project! See https://github.com/directus/directus/discussions/2975 for more details

---
# **Summary**

Allow items to be changed, but not committed to the database yet. This allows editors to make and save changes, but not have those changes published yet. This unlocks more content-specific editing workflows.

# **Basic example**

When changes on an item are made, these changes can be “soft-saved” to a new “branch”, which then allows the editor to continue working on the changes in the item, without committing to saving (”publishing”) the item to the database yet.

# **Motivation**

This allows content teams to enrich their workflows by allowing editors to make and preview changes, without publishing them yet. Without allowing saving future revisions, there’s currently no good way to achieve a similar workflow. The closest workaround is setting up a duplicate table with a flow or custom hook that will keep content in sync from one table to another, but this is non-trivial to achieve for such a common use case.

# **Detailed design**

### App Usability

On the item detail page, users will be able to create a new “Branch” from the current item. When you switch from the “Main” branch to a new branch changes made will be saved to `directus_revisions` rather than the actual table. This means users can make changes, and keep updating those changes over time, without committing to saving the changes to the database. When the user switches between branches, the current item will be loaded in from the actual table (the published item), and the saved changes will be applied. This system is very similar to the current way “Revert” works from Revisions. When the published item is changed while working on a branch revision, we show the user a warning and (if need be) a confirmation to choose whether to keep the changes made, or use the value saved to the database.

When a user is ready to commit the item to the main branch, and the user has permissions to update the main branch, a secondary save action will allow the user to preview all the changes that will be applied to the main branch, and commit the changes to the main branch.

### API Previewing

In order to enable previewing of edits in a branch, a new query parameter or endpoint will be designed that allows the user to pull in a given revision for an item.

### Must haves
- [ ] User can create new branches with a custom name
- [ ] User can switch branches at will
- [ ] User can rename an existing branch
- [ ] User can delete a branch
- [ ] Permissions can be configured for who is allowed to created “branches”
- [ ] Staged changes are saved to Revisions when in a branch that’s not the “main” branch
- [ ] Revisions saved to a branch can be “previewed” through the API
- [ ] User gets notified when changes happened on the “main” branch since they started their branch 

### Should haves

- [ ]  Allow the user to choose if they wanna keep their changes, or use the changes in the “main” update (field-by-field)

### Could haves
- [ ]  Comparison “merge” UI that shows all changes and allows final editor to save the changes
- [ ]  An ability to leave a “commit message” on saves
- [ ]  Additional UI to compare various revisions (explore branches/revisions)
- [ ]  The ability to mark a revision in a branch as “ready for review”
- [ ]  Show comments made on current branch
- [ ]  Flow operation to “advance” revision to published
- [ ]  Limit/Control the number of revisions allowed

### Will not have (at this time)
-  Multi-user collaborative editing

# **Drawbacks**

Comments and Shares might have to be adjusted to be branch-specific.

# **Alternatives**

Instead of saving just the delta to Directus Revisions, a secondary “cloned” table could be considered, however there’s some downsides to that approach:

1. It would destroy the usage of unique constraints and foreign keys
Seeing we would have to make a full copy of the table in order to allow people to make multiple copies of the item, it would mean that one to many relationships and unique constraints would be impossible
2. Tracking nested changes to relationships would entail also having duplicate tables for any of the related items down the whole tree, which in turn means you can end up with a copy of the whole database, just to keep track of branched changes for a single table

# **Adoption strategy**

This would be an opt-in additional feature; there’s no breaking changes or migration path necessary.

# **Unresolved questions**

- If you don’t have update permissions to the actual item, how do you control what fields can be edited as part of a branch:
    - Permissions for directus_branches controls who can do what to branches
    - Permissions for branches can be controlled on either the Branches row under System, or from the collection row (which is aggregated to the Branches permissions row)
    - Two new permissions “actions” will be added: `merge` and `commit`
    - Merge
        - The `merge` permissions will control when the data on a branch is allowed to be merged, and who is allowed to do this merge action
        - Merging is effectively acting like an Upsert. When the branch is updating an existing item, the commit changes are applied to the existing item, otherwise a new item is created
    - Commit
        - A commit controls what data is allowed to be saved to a specific commit
        - For the MVP, the only permission that is configured is the `fields` that can be edited in a commit
    - • Branching: Enable / Disable
    • Create Branches -> Saves to `directus_branches`
    • Read Branches -> Saves to `directus_branches`
    • Update Branches -> Saves to `directus_branches`
    • Control Commits (fields you can work with) -> Saves to `[[collection]] COMMIT` permissions
    • Merge Commits -> Saves to `[[collection]] MERGE` permissions
    • Delete Branches -> Saves to `directus_branches`
    
    ### Bulk Commit/Releases
    
    Allow users to create a “Release” that will have multiple items from one or more collections bundled. When committing a “Release” all associated “Branch” items would be applied.
    
    ### Project Release/Branch Features
    
    Should the same branching / revision logic be available for schema / settings?
    
    - Data Model Changes
        - Include the ability to add new field(s) to a collection as a “Branch”
            - New/Update item “Branch” would allow option to include new data model branch
            - Delete a data model “Branch” options:
                - Cascade delete item branch
                - Remove/Null in the item branch
    - Flows
    - Roles/Permissions
    - Project Level:
        - Env Configs
        - Project Settings
        - Presets & Bookmarks
        - etc

```[tasklist]
### Tasks
- [ ] https://github.com/directus/directus/issues/19917
- [ ] https://github.com/directus/directus/issues/19918
- [ ] https://github.com/directus/directus/issues/19920
- [ ] https://github.com/directus/directus/issues/19999
```
