### ISSUE TITLE
Add secure context for server-extensions

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#19802]
```[tasklist]
### Tasks
- [ ] https://github.com/directus/directus/issues/19853
- [ ] https://github.com/directus/directus/issues/19854
- [ ] https://github.com/directus/directus/issues/19855
- [ ] https://github.com/directus/directus/issues/19856
- [ ] https://github.com/directus/directus/issues/19804
- [ ] https://github.com/directus/directus/issues/19921
- [ ] https://github.com/directus/directus/issues/19967
- [ ] https://github.com/directus/directus/issues/19988
```
