### ISSUE TITLE
Relations

### ISSUE THREAD

**Issue by jaads** [directus/directus#19846]
Goal is to implement individual functionality in the Postgres driver first, and then port that logic to the other drivers

```[tasklist]
### Tasks
- [ ] https://github.com/directus/directus/issues/19839
- [ ] https://github.com/directus/directus/issues/19843
- [ ] https://github.com/directus/directus/issues/19767
- [ ] https://github.com/directus/directus/issues/19847
```

**Comment by jaads** [comment]
no idea how this got here, getting the feeling that tasks are a bit buggy currently
