### ISSUE TITLE
Support one to many relationships

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#19930]
```[tasklist]
### Tasks
- [ ] https://github.com/directus/directus/issues/19931
- [ ] https://github.com/directus/directus/issues/20408
- [ ] https://github.com/directus/directus/issues/19932
```
