### ISSUE TITLE
QA - Next Minor Release

### ISSUE THREAD

**Issue by alexchopin** [directus/directus#20043]
### Improvement before the release

Please reports in the task-list all QA related issues for the Next Minor Release.
```[tasklist]
### Tasks
- [ ] https://github.com/directus/directus/issues/20044
- [ ] https://github.com/directus/directus/issues/20046
- [ ] https://github.com/directus/directus/issues/20048
- [ ] https://github.com/directus/directus/issues/20050
- [ ] https://github.com/directus/directus/issues/20061
- [ ] https://github.com/directus/directus/issues/20062
- [ ] https://github.com/directus/directus/issues/20064
- [ ] https://github.com/directus/directus/issues/20081
- [ ] https://github.com/directus/directus/issues/20085
- [ ] https://github.com/directus/directus/issues/20086
- [ ] https://github.com/directus/directus/pull/20124
```
