### ISSUE TITLE
Theming Enhancements

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#20137]
## Must Haves

```[tasklist]
### Tasks
- [ ] https://github.com/directus/directus/issues/20391
- [ ] https://github.com/directus/directus/issues/20141
```

## Should Haves

```[tasklist]
### Tasks
- [ ] https://github.com/directus/directus/issues/20140
- [ ] https://github.com/directus/directus/issues/20283
- [ ] https://github.com/directus/directus/issues/20312
- [ ] https://github.com/directus/directus/issues/20637
- [ ] Add ability to save overrides as new theme
- [ ] Add "barsize" global
- [ ] Add "page info" box scope (eg the "No Items" etc icons)
- [ ] Add "card" scope (eg for file library)
- [ ] Add "panel" scope
- [ ] Add "dropdown" scope
- [ ] Make sure v-table uses proper variables
- [ ] Make sure relational interface v-lists use proper variables
- [ ] Add "Spacing" scope(s) (page, form, inputs, nav, etc)
- [ ] Fix "Search Bar" input styling and vars
- [x] Rename "Theming" to "Appearance" in settings sidebar
- [ ] https://github.com/directus/directus/issues/20192
- [ ] https://github.com/directus/directus/issues/20322
- [ ] https://github.com/directus/directus/issues/20138
- [ ] https://github.com/directus/directus/issues/20139
- [ ] https://github.com/directus/directus/issues/20274
- [ ] https://github.com/directus/directus/issues/20323
- [ ] https://github.com/directus/directus/issues/20325
- [ ] https://github.com/directus/directus/issues/20328
- [ ] https://github.com/directus/directus/issues/20276
- [ ] https://github.com/directus/directus/issues/20279
```

**Comment by rijkvanzanten** [comment]
Closing this in favor of tracking the individual sub issues 🙂
