### ISSUE TITLE
[App] Migrate authentication and refreshing to the SDK

### ISSUE THREAD

**Issue by br41nslug** [directus/directus#20810]
As the first actual migration step we'll start by moving the App authentication functions (login, logout, refresh) to use the SDK.
```[tasklist]
### Tasks
- [x] Refactor token management to be SDK instead of axios
- [x] Add shares login options to the authentication handler SDK
- [x] Replace the login/logout function in the App
- [x] Replace the refresh logic in the App
- [x] Implement SSO logins in the SDK
- [x] Test idle tab tracker logic
```
