### ISSUE TITLE
[App] Migrate interfaces to the SDK

### ISSUE THREAD

**Issue by br41nslug** [directus/directus#21000]
```[tasklist]
### Tasks
- [ ] Migrate `System Sc Interface`
- [ ] Migrate `System Token Interface`
- [ ] Migrate `Collection Item Dropdown Interface`
- [ ] Migrate `File Interface`
- [ ] Migrate `File Image Interface`
- [ ] Migrate `Input Autocomplete API Interface`
- [ ] Migrate `Input Block Editor Interface`
- [ ] Migrate `Input Rich Text HTML Interface`
```

**Comment by rijkvanzanten** [comment]
Being rearchitected as a new project
