### ISSUE TITLE
[App] Migrate modules to the SDK

### ISSUE THREAD

**Issue by br41nslug** [directus/directus#21001]
```[tasklist]
### Tasks
- [ ] Migrate `Activity Module`
- [ ] Migrate `Content Module`
- [ ] Migrate `Files Module`
- [ ] Migrate `Insights Module`
- [ ] Migrate `Settings -> Data Model Module`
- [ ] Migrate `Settings -> Field Detail Module`
- [ ] Migrate `Settings -> Extensions Module`
- [ ] Migrate `Settings -> Flows Module`
- [ ] Migrate `Settings -> Presets Module`
- [ ] Migrate `Settings -> Roles Module`
- [ ] Migrate `Settings -> Permissions Detail Module`
- [ ] Migrate `Settings -> Translations Module`
- [ ] Migrate `Settings -> WebHooks Module`
- [ ] Migrate `Users Module`
```

**Comment by rijkvanzanten** [comment]
Being rearchitected as a new project
