### ISSUE TITLE
[App] Migrate views to the SDK

### ISSUE THREAD

**Issue by br41nslug** [directus/directus#21002]
```[tasklist]
### Tasks
- [x] Migrate `basic-import-sidebar-detail` in Private View
- [x] Migrate `component-input` in Private View
- [x] Migrate `comment-item-header` in Private View
- [x] Migrate `comment-item` in Private View
- [x] Migrate `comments-sidebar-detail` in Private View
- [x] Migrate `drawer-batch` in Private View
- [x] Migrate `drawer-item` in Private View
- [x] Migrate `export-sidebar-detail` in Private View
- [x] Migrate `files-navigation-folder` in Private View
- [x] Migrate `flow-sidebar-detail` in Private View
- [x] Migrate `image-editor` in Private View
- [x] Migrate `notification-drawer` in Private View
- [x] Migrate `shares-sidebar-detail` in Private View
- [x] Migrate `user-popover` in Private View
- [x] Migrate `users-invite` in Private View
- [ ] Fix resulting type issues
```
