### ISSUE TITLE
Enhance Performance, Telemetry and Limits

### ISSUE THREAD

**Issue by licitdev** [directus/directus#21980]
Directus will greatly benefit from the addition of enhanced telemetry reporting and limit management, empowering system administrators with comprehensive insights and control over system usage. 

This issue aims to implement improved telemetry reporting and introduce limits for various aspects of the system, including user registration, activity & revisions retention, and telemetry metrics.

```[tasklist]
### Tasks
- [ ] https://github.com/directus/directus/issues/21981
- [ ] https://github.com/directus/directus/issues/17894
- [ ] https://github.com/directus/directus/issues/21982
```
