### ISSUE TITLE
No good way to fetch permissions or policies in hook extensions

### ISSUE THREAD

**Issue by u12206050** [directus/directus#23318]
### Describe the Improvement

Before Directus 11, the permissions were available on the context.accountability object.
In Directus 11, this is no longer the case, and looking at the Directus code, the go to approach seems to be making use of these two functions:

```
import { fetchPermissions } from '@directus/api/permissions/lib/fetch-permissions';
import { fetchPolicies } from '@directus/api/permissions/lib/fetch-policies';
```

As you can see though, neither is actually exported for us developers to use, this above works, but is a hack, and throws type errors.

I am aware the Permissions Items Service is available too query the raw permissions, but looking at these functions they do some smart caching which I think is very beneficial to build on top of, instead of having to reinvent the wheel.

I suggest these two functions are either added asap somewhere so we can make use of them, either via services or utils.
```[tasklist]
### Tasks
- [ ] Make validateAccess accessible
- [ ] Make validateItemAccess accessible
- [ ] Make validateCollectionAccess accessible
- [ ] Make fetchPolicies accessible
- [ ] Make fetchPermissions accessible
```

**Comment by u12206050** [comment]
My current solution:

```
/* eslint-disable @typescript-eslint/ban-ts-comment */
import type { FetchPermissionsOptions } from '@directus/api/dist/permissions/lib/fetch-permissions';
import type { Context } from '@directus/api/dist/permissions/types';
// @ts-ignore
import { fetchPermissions } from '@directus/api/permissions/lib/fetch-permissions';
// @ts-ignore
import { fetchPolicies } from '@directus/api/permissions/lib/fetch-policies';

import type { ValidateAccessOptions } from '@directus/api/dist/permissions/modules/validate-access/validate-access';
// @ts-ignore
import { validateAccess } from '@directus/api/permissions/modules/validate-access/validate-access';
import { Accountability, EventContext, Permission } from '@directus/types';

export async function getPermissions(
	options: Omit<FetchPermissionsOptions, 'policies' | 'accountability'> & {
		accountability: Pick<Accountability, 'user' | 'role' | 'roles' | 'app'>;
	},
	context: Pick<EventContext, 'database' | 'schema'>
) {
	const ctx: Context = {
		knex: context.database,
		schema: context.schema!,
	};
	const policies = await fetchPolicies(options.accountability, ctx);
	return (await fetchPermissions(
		{
			...options,
			policies,
		},
		ctx
	)) as Permission[];
}

export async function can(options: ValidateAccessOptions, context: Pick<EventContext, 'database' | 'schema'>) {
	const ctx: Context = {
		knex: context.database,
		schema: context.schema!,
	};

	return validateAccess(options, ctx) as Promise<void>;
}

```
