### ISSUE TITLE
Move from directus_table_adapters to config file and implement file library

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#805]
Just wanted to give this its own ticket... I think we both agreed that it should be in the config (maybe as an array of adapters so there can still be multiple?) and not in the DB. Also, I know you mentioned using a library that handles all the different places a developer might want to store assets... so we should implement that too (if it still looks like a good option)!

**Comment by WellingGuzman** [comment]
## TODO's
- [ ] Multiple Adapter configuration
- [ ] Better object wrapper structure
- [ ] Easy way to add more adapter with little code

**Comment by WellingGuzman** [comment]
We need to first clean all the remaining reference to the old `directus_adapter_storage` table.
