### ISSUE TITLE
"meta" key is required error when applying schema snapshot

### ISSUE THREAD

**Issue by keesvanbemmel** [directus/directus#8208]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When applying a snapshot I'm getting this error:

Error: "meta" key is required at CollectionsService.updateOne (/src/node_modules/directus/dist/services/collections.js:271:19) at /src/node_modules/directus/dist/utils/apply-snapshot.js:46:42

Now I'm guessing that the "updates" variable defined [here](https://github.com/directus/directus/blob/ce104b6a9ccf7b9b1cccf820dbc3f5bbeafe1e94/api/src/utils/apply-snapshot.ts#L48) doesn't always add the meta key, even though it's required by the CollectionsService.

### To Reproduce

I cannot share the two schema yaml files that I applied after eachoter. If need be I can gladly jump on a call to show/discuss!

### What version of Directus are you using?

rc93

### What version of Node.js are you using?

14 lts

### What database are you using?

mysql

### What browser are you using?

irrelevant

### What operating system are you using?

alpine I believe

### How are you deploying Directus?

Docker

**Comment by keesvanbemmel** [comment]
So I figured out why this happened and it doesn't seem to be a bug, which is why I'll close this issue.

For people that are running into the same error message:
In my case I created a snapshot of the schema locally and applied it in the cloud. The first time this worked but after that (when the schema was already applied) subsequent apply of the schema rendered this error. I was expecting it to tell me "Schema already up to date".

Anyway the root cause(s):
1. my local database was named differently than the database in the cloud
2. The collation of the local database was different from the one in the cloud

At the moment these should be the same on all environments for this schema snapshot functionality to work as in my case it rendered some unexpected behavior (working one time and erroring out the other). 

Furthermore it's always good practice to keep environments similar :)

@rijkvanzanten Perhaps it's a good idea to check database/shema name and collation upon applying a snapshot in the CLI but that is more of an improvement rather than a bug.

**Comment by rijkvanzanten** [comment]
I don't think the database name is stored in the snapshot, so that shouldn't be a problem. The collation is technically a difference in the snapshot compared to the database, so Directus will in fact then consider it a thing that needs to be updated.

You correctly figured out why it tried updating, but that doesn't necessarily explain to me why it failed with a "Meta is required" error though... If the collation was causing the problem, I would've expected something like "Can't setup relation due to type mismatch" or something along those lines 🤔 

I'll reopen this to see if we can figure out where that missing meta thing is coming from 🙂

**Comment by keesvanbemmel** [comment]
If you need help reproducing it, let me know! I took the snapshot from a db with the latin_swedish collation and applied it to a db with utf8_general_ci collation. Subsequent applying of the same snapshot gave me the error.

**Comment by keesvanbemmel** [comment]
FYI: I switched from mysql to postgres 12 locally and tried to apply the mysql generated schema.yaml and I got the exact same meta key is required error

**Comment by rgonzlz** [comment]
I got the same problem. I Just modify manually the SQL (I need to change the PK in an table) of the yaml and throw the error.

Maybe throws because the original SQL schema is not the same in the snapshot? 🤔 (but it haven't sense)

I'm using SQLite.

**Comment by rijkvanzanten** [comment]
Quick heads up: Make sure to create a new snapshot before checking this to make sure you don't run into https://github.com/directus/directus/issues/8318 👍🏻
