### ISSUE TITLE
Meta `filter_count` doesn't work

### ISSUE THREAD

**Issue by HitomiTenshi** [directus/directus#8253]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Version `v9.0.0-rc.94` broke the REST API:

```
Sep 22 23:56:20 directus[846840]: 23:56:20 ✨ request errored GET 500 /items/products?meta=filter_count&limit=16&page=1&fields=id,title,price,image.id,image.title,translations.title 6ms
Sep 22 23:56:20 directus[846840]:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
Sep 22 23:56:20 directus[846840]:     at runMicrotasks (<anonymous>)
Sep 22 23:56:20 directus[846840]:     at /opt/directus/node_modules/directus/dist/controllers/items.js:72:36
Sep 22 23:56:20 directus[846840]:     at MetaService.getMetaForQuery (/opt/directus/node_modules/directus/dist/services/meta.js:20:54)
Sep 22 23:56:20 directus[846840]:     at Array.map (<anonymous>)
Sep 22 23:56:20 directus[846840]:     at /opt/directus/node_modules/directus/dist/services/meta.js:24:29
Sep 22 23:56:20 directus[846840]:     at MetaService.filterCount (/opt/directus/node_modules/directus/dist/services/meta.js:66:20)
Sep 22 23:56:20 directus[846840]:     at Function.keys (<anonymous>)
Sep 22 23:56:20 directus[846840]: TypeError: Cannot convert undefined or null to object
Sep 22 23:56:20 directus[846840]: 23:56:20 🚨 Cannot convert undefined or null to object
```

This query used to work in `v9.0.0-rc.93`.

### To Reproduce

No idea as of now, try the options from this query: `/items/products?meta=filter_count&limit=16&page=1&fields=id,title,price,image.id,image.title,translations.title`

### What version of Directus are you using?

v9.0.0-rc.94

### What version of Node.js are you using?

14.17.6

### What database are you using?

MariaDB 10.3.31

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

running locally via npm package

**Comment by HitomiTenshi** [comment]
It probably has something to do with one of these options: `meta=filter_count`, `limit=16`, `page=1`

My detail page queries that don't do any pagination work fine.

**Comment by azrikahar** [comment]
> It probably has something to do with one of these options: `meta=filter_count`, `limit=16`, `page=1`
> 
> My detail page queries that don't do any pagination work fine.

Is this a particular page in the admin app, or you're calling the REST API from somewhere else via SDK or manually? just wondering how the query params are constructed (either via the admin app, directus SDK, or your own client/app).

**Comment by HitomiTenshi** [comment]
@azrikahar It's constructed by my own client (`Angular 12 HTTP Client`), I retrieved this error from the server. The client only gets a status code 500 when requesting.

This seems to happen only when pagination is being used, my detail product pages were all unaffected. Only the main page where I display many products paginated (without any filters applied yet) doesn't work.

**Comment by rijkvanzanten** [comment]
I'm not able to reproduce this on my end in a new installation..

<img width="932" alt="CleanShot 2021-09-23 at 13 38 38@2x" src="https://user-images.githubusercontent.com/9141017/134556823-80093b4c-5970-4b09-99d9-adfa353c9511.png">


Does the same problem happen in every collection? Would you be able to share a schema snapshot / database dump where this is happening for us to reproduce with?

**Comment by HitomiTenshi** [comment]
@rijkvanzanten I sent you a schema and partial dump to your email, hope it helps! 😄

**Comment by vasani-arpit** [comment]
@rijkvanzanten I am facing the same issue in all collections when I use `meta` parameter. Let me know what info do you need.

**Comment by rijkvanzanten** [comment]
I tried it using the dump you provided on email @HitomiTenshi (Thanks!), but can't seem to reproduce it with that neither..

![CleanShot 2021-09-27 at 17 37 46@2x](https://user-images.githubusercontent.com/9141017/134989020-73ac31c5-ed98-43f5-8f89-7978af4adb6a.png)

It seems like your dump only included the "products" table, but not the collections that are used in the relationships (in this case "image" and "translations"), so I can't exclude that the problem exists somewhere in the nested relational chain.

**Comment by joey-d** [comment]
No idea how to reproduce it. There is a Many to Many field. The many to many field is not selected on the query with the meta filter.

**Comment by vasani-arpit** [comment]
@rijkvanzanten here is my dump. https://hatbat.in/download/7a9679d7c1ae3cec/#Z-zqb51RAHd8GxEZgeH2QA 
it will be destroyed after few days. 

try this collection/endpoint after importing 
[http://localhost:8085/items/usersearnpoint?meta=*](http://localhost:8085/items/usersearnpoint?meta=*)

**Comment by rijkvanzanten** [comment]
Thanks @vasani-arpit! For what it's worth, you can upload zip's straight to GitHub 🙂 That'll also prevent it from disappearing after a few days (however many that is) which would prevent others from ever reproducing this

**Comment by rijkvanzanten** [comment]
Looks like it's a bug in permissions. When `permissions` is set so `NULL` instead of `{}`, the request fails with the mentioned error in the OP.
