### ISSUE TITLE
Edits tracking always true after any edit in Data Model Settings

### ISSUE THREAD

**Issue by licitdev** [directus/directus#8565]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

After any change is made and reverted, the edits tracking does not revert back, as reflected by the `Save` button.

https://user-images.githubusercontent.com/26413686/136057891-482771e8-9f05-4da8-af89-3ef2aa2c1bde.mov

### To Reproduce

1. Open Settings > Data Model
2. Open a collection (non-system)
3. Make a change in any field
4. Undo the change
5. Notice that the `Save` button is lit up even when no changes made

### What version of Directus are you using?

main branch

### What version of Node.js are you using?

v16

### What database are you using?

Postgres

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment]
"Clear Value" !== undoing the change though. Clear Value is setting the field to `null`. That being said, if the value was already `null` before, it should unset the staged change, instead of setting the value to `null` (again)
